Weekly_Program_Solution/WP_Web/Models/Lesson.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace WP_Web.Models
{
    public class Lesson
    {
        public int LessonId { get; set; }
        public Guid UserId { get; set; }
        public User User { get; set; }
        public int AcademicYearId { get; set; }
        public AcademicYear AcademicYear { get; set; }
        public string Name { get; set; }
    }
}

Weekly_Program_Solution/WP_Web/Controllers/LessonsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using WP_Web.Models;

namespace WP_Web.Controllers
{
    public class LessonsController : Controller
    {
        private WPDB db = new WPDB();

        private AuthenticatedUser AuthInfo
        {
            get
            {
                if (Session["Auth"] == null)
                    return new AuthenticatedUser { Authenticated = false };

                return (AuthenticatedUser)Session["Auth"];
            }
        }

        private User CurrentUser
        {
            get
            {
                return db.Users.Where(u => u.Email == AuthInfo.Email).FirstOrDefault();
            }
        }

        private AcademicYear CurrentAcademicYear
        {
            get
            {
                if (Session["CurrentAcademicYear"] == null)
                    return new AcademicYear { AcademicYearId = -1 };

                return (AcademicYear)Session["CurrentAcademicYear"];
            }
        }

        // GET: Lessons
        public ActionResult Index()
        {
            if (!AuthInfo.Authenticated)
                return RedirectToAction("Login", "Home");

            if (CurrentAcademicYear.AcademicYearId == -1)
            {
                return RedirectToAction("Index", "AcademicYears");
            }

            var lessons = db.Lessons
                .Where(l => l.AcademicYearId == CurrentAcademicYear.AcademicYearId &&
                            l.UserId == CurrentUser.UserId)
                .OrderBy(l=>l.Name);
            

            return View(lessons.ToList());
        }

        [HttpGet]
        public ActionResult Search()
        {
            if (!AuthInfo.Authenticated)
                return RedirectToAction("Login", "Home");

            if (CurrentAcademicYear.AcademicYearId == -1)
            {
                return RedirectToAction("Index", "AcademicYears");
            }

            return PartialView("_SearchFormPartial");
        }

        [HttpPost]
        public ActionResult Search(string filter)
        {
            if (!AuthInfo.Authenticated)
                return RedirectToAction("Login", "Home");

            if (CurrentAcademicYear.AcademicYearId == -1)
            {
                return RedirectToAction("Index", "AcademicYears");
            }

            var lessons = db.Lessons
                .Where(l => l.AcademicYearId == CurrentAcademicYear.AcademicYearId &&
                            l.UserId == CurrentUser.UserId);

            if (filter != string.Empty)
                lessons = lessons.Where(l => l.Name.StartsWith(filter));

            lessons = lessons.OrderBy(l => l.Name);

            return PartialView("_SearchResultPartial", lessons.ToList());
        }

        // GET: Lessons/Create
        public ActionResult Create()
        {
            if (!AuthInfo.Authenticated)
                return RedirectToAction("Login", "Home");

            if (CurrentAcademicYear.AcademicYearId == -1)
            {
                return RedirectToAction("Index", "AcademicYears");
            }
            
            return View();
        }

        // POST: Lessons/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "LessonId,Name")] Lesson lesson)
        {
            if (!AuthInfo.Authenticated)
                return RedirectToAction("Login", "Home");

            if (CurrentAcademicYear.AcademicYearId == -1)
            {
                return RedirectToAction("Index", "AcademicYears");
            }

            if (ModelState.IsValid)
            {
                lesson.AcademicYearId = CurrentAcademicYear.AcademicYearId;
                lesson.UserId = CurrentUser.UserId;

                db.Lessons.Add(lesson);
                db.SaveChanges();

               return Redirect(Request.UrlReferrer.ToString());
            }

            return View(lesson);
        }

        // GET: Lessons/Edit/5
        public ActionResult Edit(int? id)
        {
            if (!AuthInfo.Authenticated)
                return RedirectToAction("Login", "Home");

            if (CurrentAcademicYear.AcademicYearId == -1)
            {
                return RedirectToAction("Index", "AcademicYears");
            }

            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Lesson lesson = db.Lessons
                 .Where(l => l.AcademicYearId == CurrentAcademicYear.AcademicYearId &&
                            l.UserId == CurrentUser.UserId &&
                            l.LessonId == id)
                .FirstOrDefault();

            if (lesson == null)
            {
                return HttpNotFound();
            }
            return View(lesson);
        }

        // POST: Lessons/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "LessonId,Name")] Lesson lesson)
        {
            if (ModelState.IsValid)
            {
                db.Entry(lesson).State = EntityState.Modified;
                lesson.UserId = CurrentUser.UserId;
                lesson.AcademicYearId = CurrentAcademicYear.AcademicYearId;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(lesson);
        }

        // GET: Lessons/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Lesson lesson = db.Lessons
                .Where(l => l.AcademicYearId == CurrentAcademicYear.AcademicYearId &&
                            l.UserId == CurrentUser.UserId &&
                            l.LessonId == id)
                .FirstOrDefault();
            if (lesson == null)
            {
                return HttpNotFound();
            }
            return View(lesson);
        }

        // POST: Lessons/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Lesson lesson = db.Lessons
                .Where(l => l.AcademicYearId == CurrentAcademicYear.AcademicYearId &&
                            l.UserId == CurrentUser.UserId &&
                            l.LessonId == id)
                .FirstOrDefault();
            db.Lessons.Remove(lesson);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Weekly_Program_Solution/WP_Web/Views/Lessons/Create.cshtml
@model WP_Web.Models.Lesson

@{
    Layout = null;
}

    
    
    @using (Html.BeginForm("Create", "Lessons", FormMethod.Post)) 
    {
        @Html.AntiForgeryToken()
        
        <div class="form-horizontal">
            <h4>Lesson</h4>
            <hr />
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    
            <div class="form-group">
                @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
                </div>
            </div>
    
            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="Create" class="btn btn-default" />
                </div>
            </div>
        </div>
    }
    
   

Weekly_Program_Solution/WP_Web/Views/Lessons/Delete.cshtml
@model WP_Web.Models.Lesson

@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Delete</title>
</head>
<body>
    <h3>Are you sure you want to delete this?</h3>
    <div>
        <h4>Lesson</h4>
        <hr />
        <dl class="dl-horizontal">
            
            <dt>
                @Html.DisplayNameFor(model => model.Name)
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.Name)
            </dd>
    
        </dl>
    
        @using (Html.BeginForm()) {
            @Html.AntiForgeryToken()
    
            <div class="form-actions no-color">
                <input type="submit" value="Delete" class="btn btn-default" /> |
                @Html.ActionLink("Back to List", "Index")
            </div>
        }
    </div>
</body>
</html>

Weekly_Program_Solution/WP_Web/Views/Lessons/Details.cshtml
@model WP_Web.Models.Lesson

@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Details</title>
</head>
<body>
    <div>
        <h4>Lesson</h4>
        <hr />
        <dl class="dl-horizontal">
            <dt>
                @Html.DisplayNameFor(model => model.AcademicYear.Title)
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.AcademicYear.Title)
            </dd>
    
            <dt>
                @Html.DisplayNameFor(model => model.User.Email)
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.User.Email)
            </dd>
    
            <dt>
                @Html.DisplayNameFor(model => model.Name)
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.Name)
            </dd>
    
        </dl>
    </div>
    <p>
        @Html.ActionLink("Edit", "Edit", new { id = Model.LessonId }) |
        @Html.ActionLink("Back to List", "Index")
    </p>
</body>
</html>

Weekly_Program_Solution/WP_Web/Views/Lessons/Edit.cshtml
@model WP_Web.Models.Lesson

@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Edit</title>
</head>
<body>
    <script src="~/Scripts/jquery-1.10.2.min.js"></script>
    <script src="~/Scripts/jquery.validate.min.js"></script>
    <script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>
    
    
    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()
        
        <div class="form-horizontal">
            <h4>Lesson</h4>
            <hr />
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            @Html.HiddenFor(model => model.LessonId)
    
    
            <div class="form-group">
                @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
                </div>
            </div>
    
            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="Save" class="btn btn-default" />
                </div>
            </div>
        </div>
    }
    
    <div>
        @Html.ActionLink("Back to List", "Index")
    </div>
</body>
</html>

Weekly_Program_Solution/WP_Web/Views/Lessons/Index.cshtml
@model IEnumerable<WP_Web.Models.Lesson>

@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Index</title>
</head>
<body>
    <p>
        @Html.ActionLink("Create New", "Create")
    </p>
    <table class="table">
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Name)
            </th>
            <th></th>
        </tr>
    
    @foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Name)
            </td>
            <td>
                @Html.ActionLink("Edit", "Edit", new { id=item.LessonId }) |
                @Html.ActionLink("Delete", "Delete", new { id=item.LessonId })
            </td>
        </tr>
    }
    
    </table>
</body>
</html>

Weekly_Program_Solution/WP_Web/Views/Lessons/List.cshtml
@model IEnumerable<WP_Web.Models.Lesson>

@using (Html.BeginForm("List", "Lessons"))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })

        <div class="form-group">
            @Html.Label("filterlabel", "جستجو", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextBox("filter","", new { htmlAttributes = new { @class = "form-control" } })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Go" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<table class="table">
    <tr>
        
        <th>
            @Html.DisplayNameFor(model => model.Name)
        </th>
    </tr>

@foreach (var item in Model) {
    <tr>
       
        <td>
            @Html.DisplayFor(modelItem => item.Name)
        </td>
       
    </tr>
}

</table>

Weekly_Program_Solution/WP_Web/Views/Lessons/_SearchFormPartial.cshtml
@using (Ajax.BeginForm("Search", "Lessons", FormMethod.Post,
        new AjaxOptions
        {
            InsertionMode = InsertionMode.Replace,
            HttpMethod = "POST",
            UpdateTargetId = "search-results"
        }))
{
    <div>
        @Html.TextBox("filter")
        <input type="submit" value="جستجو" onclick=""/>
    </div>
}

Weekly_Program_Solution/WP_Web/Views/Lessons/_SearchResultPartial.cshtml
@model IEnumerable<WP_Web.Models.Lesson>
@if (Model.Count() == 0)
{
    <h3 class="text-error">چنین درسی وجود ندارد. </h3>
}
else
{
    <table class="table">
        <tr>

            <th>
                @Html.DisplayNameFor(model => model.Name)
            </th>
        </tr>

        @foreach (var item in Model)
        {
            <tr>

                <td>
                    @Html.DisplayFor(modelItem => item.Name)
                </td>

            </tr>
        }

    </table>
}