Weekly_Program_Solution/WP_Web/Models/AcademicYear.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;

namespace WP_Web.Models
{
    public class AcademicYear
    {
        [Key]
        public int AcademicYearId { get; set; }
        public Guid UserId { get; set; }
        public virtual User User { get; set; }
        public string Title { get; set; }
        public int DefaultRingCount { get; set; }

        //public virtual ICollection<Teacher> Teachers { get; set; }
    }
}

Weekly_Program_Solution/WP_Web/Models/AcademicYears.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;

namespace WP_Web.Models
{
    public class AcademicYear
    {
        [Key]
        public int AcademicYearId { get; set; }
        public Guid UserId { get; set; }
        public virtual User User { get; set; }
        public string Title { get; set; }
    }
}

Weekly_Program_Solution/WP_Web/Controllers/AcademicYearsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using WP_Web.Models;

namespace WP_Web.Controllers
{
    public class AcademicYearsController : Controller
    {
        private WPDB db = new WPDB();

        private AuthenticatedUser AuthInfo
        {
            get
            {
                if (Session["Auth"] == null)
                    return new AuthenticatedUser { Authenticated = false };

                return (AuthenticatedUser)Session["Auth"];
            }
        }

        private User CurrentUser
        {
            get
            {
                return db.Users.Where(u => u.Email == AuthInfo.Email).FirstOrDefault();
            }
        }

        // GET: AcademicYears
        public ActionResult Index()
        {
            if (!AuthInfo.Authenticated)
                return RedirectToAction("Login", "Home");

            var academicYears = db.AcademicYears.Include(a=>a.User)
                .Where(a => a.User.UserId == CurrentUser.UserId)
                .OrderByDescending(a => a.AcademicYearId);

            return View(academicYears.ToList());
        }

        // GET: AcademicYears/Create
        public ActionResult Create()
        {
            if (!AuthInfo.Authenticated)
                return RedirectToAction("Login", "Home");

            return View();
        }

        // POST: AcademicYears/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "AcademicYearId,Title,DefaultRingCount")] AcademicYear academicYear)
        {
            if (!AuthInfo.Authenticated)
                return RedirectToAction("Login", "Home");

            if (ModelState.IsValid)
            {
                academicYear.User = CurrentUser;
                db.AcademicYears.Add(academicYear);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(academicYear);
        }

        // GET: AcademicYears/Edit/5
        public ActionResult Edit(int? id)
        {
            if (!AuthInfo.Authenticated)
                return RedirectToAction("Login", "Home");

            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            AcademicYear academicYear = db.AcademicYears.Include(a => a.User)
                .Where(a => a.User.UserId == CurrentUser.UserId && a.AcademicYearId == id)
                .FirstOrDefault();

            if (academicYear == null)
            {
                return HttpNotFound();
            }
            return View(academicYear);
        }

        // POST: AcademicYears/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "AcademicYearId,Title,DefaultRingCount")] AcademicYear academicYear)
        {
            if (!AuthInfo.Authenticated)
                return RedirectToAction("Login", "Home");

            if (ModelState.IsValid)
            {
                db.Entry(academicYear).State = EntityState.Modified;
                academicYear.User = CurrentUser;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(academicYear);
        }

        // GET: AcademicYears/Delete/5
        public ActionResult Delete(int? id)
        {
            if (!AuthInfo.Authenticated)
                return RedirectToAction("Login", "Home");

            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            AcademicYear academicYear = db.AcademicYears.Include(a => a.User)
                .Where(a => a.User.UserId == CurrentUser.UserId && a.AcademicYearId == id)
                .FirstOrDefault();
            if (academicYear == null)
            {
                return HttpNotFound();
            }
            return View(academicYear);
        }

        // POST: AcademicYears/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            AcademicYear academicYear = db.AcademicYears.Include(a => a.User)
                .Where(a => a.User.UserId == CurrentUser.UserId && a.AcademicYearId == id)
                .FirstOrDefault();
            db.AcademicYears.Remove(academicYear);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Weekly_Program_Solution/WP_Web/Controllers/WeeklySchedulesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using WP_Web.Models;

namespace WP_Web.Controllers
{
    public class WeeklySchedulesController : Controller
    {
        private WPDB db = new WPDB();

        private AuthenticatedUser AuthInfo
        {
            get
            {
                if (Session["Auth"] == null)
                    return new AuthenticatedUser { Authenticated = false };

                return (AuthenticatedUser)Session["Auth"];
            }
        }

        private User CurrentUser
        {
            get
            {
                return db.Users.Where(u => u.Email == AuthInfo.Email).FirstOrDefault();
            }
        }

        private AcademicYear CurrentAcademicYear
        {
            get
            {
                if (Session["AcademicYear"] == null)
                    return new AcademicYear { AcademicYearId = -1 };

                return (AcademicYear)Session["AcademicYear"];
            }
        }
        // GET: WeeklySchedules
        public ActionResult Index(int? id)
        {
            if (!AuthInfo.Authenticated)
                return RedirectToAction("Login", "Home");

            if (id == null)
            {
                if (CurrentAcademicYear.AcademicYearId == -1)
                    return HttpNotFound();
                else
                    id = CurrentAcademicYear.AcademicYearId;
            }

            var currentAcademicYear = db.AcademicYears.Include(a => a.User)
                .Where(a => a.User.UserId == CurrentUser.UserId && a.AcademicYearId == id).FirstOrDefault();

            if (currentAcademicYear == null)
            {
                return RedirectToAction("Index", "AcademicYears");
            }

            Session["CurrentAcademicYear"] = currentAcademicYear;

            return View();
        }
    }
}

Weekly_Program_Solution/WP_Web/Views/AcademicYears/Create.cshtml
@model WP_Web.Models.AcademicYear

@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Create</title>
</head>
<body>
    <script src="~/Scripts/jquery-1.10.2.min.js"></script>
    <script src="~/Scripts/jquery.validate.min.js"></script>
    <script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>
    
    
    @using (Html.BeginForm()) 
    {
        @Html.AntiForgeryToken()
        
        <div class="form-horizontal">
            <h4>AcademicYear</h4>
            <hr />
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    
            <div class="form-group">
                @Html.LabelFor(model => model.Title, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Title, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Title, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.DefaultRingCount, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.DefaultRingCount, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.DefaultRingCount, "", new { @class = "text-danger" })
                </div>
            </div>
    
            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="Create" class="btn btn-default" />
                </div>
            </div>
        </div>
    }
    
    <div>
        @Html.ActionLink("Back to List", "Index")
    </div>
</body>
</html>

Weekly_Program_Solution/WP_Web/Views/AcademicYears/Delete.cshtml
@model WP_Web.Models.AcademicYear

@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Delete</title>
</head>
<body>
    <h3>Are you sure you want to delete this?</h3>
    <div>
        <h4>AcademicYear</h4>
        <hr />
        <dl class="dl-horizontal">
            
            <dt>
                @Html.DisplayNameFor(model => model.Title)
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.Title)
            </dd>
    
        </dl>
    
        @using (Html.BeginForm()) {
            @Html.AntiForgeryToken()
    
            <div class="form-actions no-color">
                <input type="submit" value="Delete" class="btn btn-default" /> |
                @Html.ActionLink("Back to List", "Index")
            </div>
        }
    </div>
</body>
</html>

Weekly_Program_Solution/WP_Web/Views/AcademicYears/Edit.cshtml
@model WP_Web.Models.AcademicYear

@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Edit</title>
</head>
<body>
    <script src="~/Scripts/jquery-1.10.2.min.js"></script>
    <script src="~/Scripts/jquery.validate.min.js"></script>
    <script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>
    
    
    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()
        
        <div class="form-horizontal">
            <h4>AcademicYear</h4>
            <hr />
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            @Html.HiddenFor(model => model.AcademicYearId)
    
            <div class="form-group">
                @Html.LabelFor(model => model.Title, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Title, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Title, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.DefaultRingCount, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.DefaultRingCount, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.DefaultRingCount, "", new { @class = "text-danger" })
                </div>
            </div>
    
            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="Save" class="btn btn-default" />
                </div>
            </div>
        </div>
    }
    
    <div>
        @Html.ActionLink("Back to List", "Index")
    </div>
</body>
</html>

Weekly_Program_Solution/WP_Web/Views/AcademicYears/Index.cshtml
@model IEnumerable<WP_Web.Models.AcademicYear>

@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Index</title>
</head>
<body>
    <p>
        @Html.ActionLink("Create New", "Create")
    </p>
    <table class="table">
        <tr>
           
            <th>
                @Html.DisplayNameFor(model => model.Title)
            </th>
            <th></th>
        </tr>
    
    @foreach (var item in Model) {
        <tr>
           
            <td>
                @Html.DisplayFor(modelItem => item.Title)
            </td>
            <td>
                @Html.ActionLink("Weekly Schedules", "Index", "WeeklySchedules", new { id = item.AcademicYearId }, null) |
                @Html.ActionLink("Edit", "Edit", new { id=item.AcademicYearId }) |
                @Html.ActionLink("Delete", "Delete", new { id=item.AcademicYearId })
            </td>
        </tr>
    }
    
    </table>
</body>
</html>